name: Unit Tests

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
    - name: Fetch repository and Checkout code
      uses: actions/checkout@v2

    # Dependencies needed for installing R dependencies
    - name: Install Linux dependencies required for installing R packages
      run: |
        sudo apt install build-essential libcurl4-gnutls-dev libxml2-dev libssl-dev
        sudo apt install libharfbuzz-dev libfribidi-dev

    - name: Install R language
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: 4.1
    
    - name: Cache R packages
      uses: actions/cache@v3
      env:
        cache-name: cache-r-libs
      with:
        path: ${{ env.R_LIBS_USER }}
        # If key changes, libraries will be reinstalled (regenerating cache)
        # We use DECRIPTION file for this key as it needs to be changed for adding
        # dependencies
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/DESCRIPTION') }}
        restore-keys: ${{ runner.os }}-build-${{ env.cache-name }}

    - name: Install R dependencies
      run: |
        R -e 'install.packages(c("devtools", "testthat"))'

    - name: Run tests
      # This command runs tests and returns appropriate status code
      run: |
        R -e 'res=devtools::test();df=as.data.frame(res);if(sum(df$failed) > 0 || any(df$error)) {q(status=1)}'
